index.html
=> Add index.html to the project

index.html, resources/style.css
Added responsive layout - media queries
Added quotes, and motivation text 
Added flexbox to cards (align)
=> Jerin version

index.html, resources/style.css
Hi There, I have added a semantic HTML footer element alongside with anchor tag links and copyright information. I have then added styling to this footer element for user visual experience.
=> Added Footer with Anchor Tag Links & Copyright Information

card.html, index.html
Sorry, guys I made a mistake when merging Prasanna's validation, I had a previous version of the index, (one without the footer), so I'm looking to update it with the new validation from Prasanna
=> fixed index and validation

README.md, archive
I also changed the title to add group-2, and capitilization
=> Added the google documentation to the readme

index.html, resources/style.css, script.js
The new index.html.  Jerin might need to create a pull request from the style.css to update the full change.
=> New pop up

index.html, resources/style.css
Added bootstrap badges
Added:
- Due date
- Status
- Assigned to
Preview:
=> Layout update

index.html, script.js
Add the validation script with bootstrap features to the default HTML form
=> fix the pop up conflicts with the validation confilcs; Add customised validation with bootstrap and javascript

index.html, resources/style.css, script.js
Added more responsiveness to the website now, since we are going to be starting javascript soon, we can adjust it more later :)
=> Responsive website

index.html, resources/style.css
- made the navbar smaller.
- added doppio one font.
=> Added new fonts, changed other fonts, adjusted navbar size

resources/style.css
=> fixed logo in mobile, added space between title edges, centered card in mobile

index.html, resources/style.css, script.js
Add validate function to group button with version 3.  Some parts need to work more in future 
Open issue  for future reference : https://github.com/tobiturner/to-do-list/issues/33
=> Add validate function to group button version 3

index.html, resources/style.css, script.js
added some functions in script.js and modifies index.html code to validate the checkbox button group.
=> DCT-6 added checkbox validation code

README.md
=> DCT-10 modified readme and added github pages website to readme

archive, card.html, index.html, resources/style.css, script.js
Using the default auto-formatting from vscode
=> DCT-11 format codes with defalt VScode format

.gitignore, index.html, resources/style.css, validate.js
=> added bootstrap modal

index.html, resources/style.css, validate.js
I changed the feedback font colors. for valid feedback green and invalid feedback red.
=> changed the feedback font colors

TaskManager.js, validate.js
Task manager v2 --- passing the value to the task object and add  into the task manager list(increment ID)
=> Task manager v2 --- passing the value to the task object and add  into the task manager list(increment ID)

index.html, validate.js
Milestone: Task7 display task: incomplete version with errors needs to fix between form and task display.
Problem: There are some new issues with submitting multiple times.  we need to reset the values and feedback and forms. 
The bugs are as follows:
1.Reset the status after submit  
2.The feedback display should be reset after submit. 
3.Reset the assignees  after submit
4.close the modal after submit
5.Task manager list do not add new task.
=> Task7 display task: incomplete version with errors need to fix between form and task display

archive/taginput.html, index.html, script.js, taginput.js
add input tags for fetch the relevant image to the form
=> Fetch relevent image v2

script.js
changed the script.js file from line 39 to line 49
=> fixed minute double digits

TaskManager.js, script.js
=> Render saved task v3-- update status function

TaskManager.js, script.js
=> Update status UI completed task 8 

script.js
=> changed pill color according to status

preLoadTasks.json, script.js
First:  Start to load JSON task objects to local storage;
Second: Rendering from Local Storage(LS) only;
Third:  disable the connection from JSON to LS  by using local storage {key: value} --> {isJsonLoaded: false -> true}  ;
Outcome: Refresh and reload the page, and the JSON file will no longer interact with local storage; The local storage has consistency with the card's display.
P.S. It is easier to do this with the backend. Such as Node.js  require('fs'). Since this library can set up communication between localStorage to JSON file. read and write 
This is an approach for the front end only.
It is fun to do but not a common approach.
=> Local storage json v2

script.js
=> add delete task UI

script.js
Refactor renderSavedFunction and clean description for code.
=> refactor renderSavedFunction and clean descrption for code

index.html, preLoadTasks.json, script.js
1 add the {tag: ["demo"]} into the JSON file to fix the display error from displaying the tag for initial Json loading.
=> Change json for fix tag

script.js
=> hot fix for the time

script.js
refactor duplication on taskobject
=> refactor duplication on taskobject

script.js
change the display due date from yyyy-mm-dd  --> dd/mm/yyyy which is consistent with the form calendar.
=> change due date format on display only

script.js
Final cleaning of the code description and comments and console log
=> Clean code
